asset_dir = "assets"
exclude_assets = []
write_dir = "src/shared/libs"

[creator]
type = "user"
id = 3851984116

[codegen]
output_name = "assets"
typescript = false
style = "flat"
strip_extension = true
