[package]
name = "th4tunkn0wndud3/coinsdemo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
DocumentService = "anthony0br/documentservice@1.2.2"
ByteNet = "ffrostflame/bytenet@0.4.6"
Guard = "red-blox/guard@^1.0.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
